"""add_debrid_url_to_downloads

Revision ID: 03073ebe632b
Revises: 21fa09bdb14d
Create Date: 2026-04-18 21:12:35.005906

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '03073ebe632b'
down_revision: str | Sequence[str] | None = '21fa09bdb14d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('debrid_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'debrid_url')
    # ### end Alembic commands ###
