"""add status and error columns to history table

Revision ID: 21fa09bdb14d
Revises: b01a6bd73c66
Create Date: 2026-04-06 20:03:23.840648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21fa09bdb14d'
down_revision: Union[str, Sequence[str], None] = 'b01a6bd73c66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('status', sa.String(length=50), nullable=False, server_default='completed'))
    op.add_column('history', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'error')
    op.drop_column('history', 'status')
    # ### end Alembic commands ###
