"""add_alternative_urls_to_downloads

Revision ID: 35316fa55864
Revises: caeccc4c120d
Create Date: 2026-04-23 22:19:21.698204

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '35316fa55864'
down_revision: str | Sequence[str] | None = 'caeccc4c120d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('downloads', sa.Column('alternative_urls', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('downloads', 'alternative_urls')
    # ### end Alembic commands ###
