"""add_destination_to_history

Revision ID: caeccc4c120d
Revises: 03073ebe632b
Create Date: 2026-04-19 13:23:02.923441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caeccc4c120d'
down_revision: Union[str, Sequence[str], None] = '03073ebe632b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('destination', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'destination')
    # ### end Alembic commands ###
